apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vdi.fullname" . }}
  labels:
    {{- include "vdi.labels" . | nindent 4 }}
type: Opaque
data:
  vncPassword: {{ .Values.vncPassword | b64enc | quote }}